name: Build

on:
  push  

jobs:
  check:
    name: Build installers from python project
    strategy:
      matrix:
        os: ['windows-latest', 'ubuntu-latest', 'macos-latest']
    runs-on: ${{ matrix.os }}
    steps:
      - name: Check out the repo
        uses: actions/checkout@v5

      - uses: actions/setup-python@v6
        with:
          python-version: 3.14

      - name: Install uv and pyinstaller
        run: pip install uv pyinstaller

      - name: Generate requirements.txt
        run: uv export --format requirements-txt > requirements.txt
        working-directory: ./lw_python

      - name: Install requirements
        run: pip install -r requirements.txt
        working-directory: ./lw_python

      - name: Build with pyinstaller
        run: pyinstaller lw_python/main.py
        working-directory: ./lw_python
        
      - uses: actions/upload-artifact@v5
        with:
          path: lw_python/dist/*