name: Build

on:
  push:
    branches: [main] 

jobs:
  check:
    name: Build installers from python project
    strategy:
      matrix:
        os: ['windows-latest', 'ubuntu-latest', 'ubuntu-24.04-arm', 'macos-latest']
    runs-on: ${{ matrix.os }}
    steps:
      - name: Check out repository
        uses: actions/checkout@v6
      - name: Prepare repository
        uses: ./.github/actions/prepare
      - name: Build 
        run: just package
      - uses: actions/upload-artifact@v5
        with:
          name: lw-python-${{ matrix.os }}
          include-hidden-files: true
          path: ./dist/*
          